# Generated by Django 5.1.7 on 2025-04-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.CharField(max_length=100)),
                ('date_fin', models.CharField(max_length=100)),
                ('annee_civile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id_diplome', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('abreviation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_universite', models.CharField(max_length=100)),
                ('nom_ecole', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('bp', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('adr_site_web', models.CharField(max_length=255)),
                ('nom_responsable_ecole', models.CharField(max_length=100)),
                ('titre_responsable_ecole', models.CharField(max_length=100)),
                ('nom_responsable_etude', models.CharField(max_length=100)),
                ('titre_responsable_etude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id_mention', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('abreviation', models.CharField(max_length=100)),
                ('moy_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('moy_max', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id_pays', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pays', models.CharField(max_length=100)),
                ('code_pays', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numProfil', models.CharField(max_length=100)),
                ('nomProfil', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id_serie', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('code_access', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Utilisateur', to='api.profil')),
            ],
        ),
    ]
