# Generated by Django 4.2.20 on 2025-05-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='poids',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
