# Generated by Django 4.2.20 on 2025-06-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eleve_poids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='id_candidat',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
