# Generated by Django 4.2.20 on 2025-06-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_candidat_id_candidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='num_table',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
