# Generated by Django 5.1.7 on 2025-04-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_utilisateur_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='code_access',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
