# Generated by Django 4.2 on 2025-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_utilisateur_code_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id_matiere', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('abreviation', models.CharField(max_length=100)),
            ],
        ),
    ]
