# Generated by Django 5.1.7 on 2025-04-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_utilisateur_code_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id_dossier', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id_jury', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id_matiere', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('abreviation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id_parametre', models.AutoField(primary_key=True, serialize=False)),
                ('duree_max_oisivete', models.IntegerField()),
                ('bonus_annee_bac', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id_specialite', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('abreviation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pays',
            name='indicatif',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pays',
            name='nationalite',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id_eleve', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('addresse', models.CharField(max_length=100)),
                ('pays_naissance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Eleve', to='api.pays')),
                ('dossier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Eleve', to='api.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='MembreJury',
            fields=[
                ('id_membre', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('jury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MembreJury', to='api.jury')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('est_preselection', models.BooleanField(default=True)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Note', to='api.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='DiplomeObtenu',
            fields=[
                ('id_diplome_obtenu', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.IntegerField()),
                ('diplome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiplomeObtenu', to='api.diplome')),
                ('mention', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiplomeObtenu', to='api.mention')),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiplomeObtenu', to='api.pays')),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiplomeObtenu', to='api.serie')),
                ('dossier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiplomesObtenus', to='api.dossier')),
                ('notes', models.ManyToManyField(related_name='DiplomesObtenus', to='api.note')),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dossier', to='api.specialite'),
        ),
        migrations.CreateModel(
            name='CoefficientMatierePhase',
            fields=[
                ('id_coeffmp', models.AutoField(primary_key=True, serialize=False)),
                ('estPreselection', models.BooleanField()),
                ('coefficient', models.IntegerField()),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CoeffMP', to='api.matiere')),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CoeffMP', to='api.specialite')),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('eleve_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.eleve')),
                ('num_table', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.ManyToManyField(related_name='Candidat', to='api.note')),
            ],
            bases=('api.eleve',),
        ),
    ]
