# Generated by Django 4.2.20 on 2025-06-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_candidat_num_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='phase_actuel',
            field=models.CharField(choices=[('préalable', 'Préalable'), ('préselection', 'Préselection'), ('écrite', 'Écrite'), ('terminé', 'Terminé')], default='préalable', max_length=20),
        ),
    ]
