# Generated by Django 4.2 on 2025-04-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_matiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('id_matiere', models.CharField(max_length=100)),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('est_preselection', models.BooleanField(default=True)),
            ],
        ),
    ]
