# Generated by Django 5.1.7 on 2025-05-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dossier_jury_matiere_parametre_specialite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivage',
            fields=[
                ('id_archive', models.AutoField(primary_key=True, serialize=False)),
                ('fichier', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dossier',
            name='date_inscription',
            field=models.DateField(auto_now_add=True),
        ),
    ]
