# Generated by Django 4.2 on 2025-04-22 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id_matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Note', to='api.matiere'),
        ),
    ]
