# Generated by Django 4.2 on 2025-04-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_note_id_matiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='id_matiere',
            new_name='matiere',
        ),
    ]
