# Generated by Django 4.2 on 2025-04-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_id_matiere_note_matiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomeObtenu',
            fields=[
                ('id_diplome_obtenu', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.DateField()),
                ('diplome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiplomeObtenu', to='api.diplome')),
                ('mention', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiplomeObtenu', to='api.mention')),
                ('notes', models.ManyToManyField(related_name='DiplomesObtenus', to='api.note')),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiplomeObtenu', to='api.pays')),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiplomeObtenu', to='api.serie')),
            ],
        ),
    ]
