# Generated by Django 4.2 on 2025-04-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_diplomeobtenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomeobtenu',
            name='annee',
            field=models.IntegerField(),
        ),
    ]
