# Generated by Django 4.2 on 2025-04-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_diplomeobtenu_annee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id_specialite', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('abreviation', models.CharField(max_length=100)),
            ],
        ),
    ]
