# Generated by Django 4.2 on 2025-04-23 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_specialite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id_dossier', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateField()),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dossier', to='api.specialite')),
            ],
        ),
        migrations.AddField(
            model_name='diplomeobtenu',
            name='dossier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiplomesObtenus', to='api.dossier'),
        ),
    ]
