# Generated by Django 4.2 on 2025-04-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dossier_diplomeobtenu_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='indicatif',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pays',
            name='nationalite',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id_eleve', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('addresse', models.CharField(max_length=100)),
                ('dossier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Eleve', to='api.dossier')),
                ('pays_naissance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Eleve', to='api.pays')),
            ],
        ),
    ]
