# Generated by Django 4.2 on 2025-04-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pays_indicatif_pays_nationalite_eleve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('eleve_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.eleve')),
                ('num_table', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('api.eleve',),
        ),
    ]
