# Generated by Django 4.2 on 2025-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_candidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='notes',
            field=models.ManyToManyField(related_name='Candidat', to='api.note'),
        ),
    ]
