# Generated by Django 4.2 on 2025-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_candidat_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id_parametre', models.AutoField(primary_key=True, serialize=False)),
                ('duree_max_oisivete', models.IntegerField()),
                ('bonus_annee_bac', models.IntegerField()),
            ],
        ),
    ]
