# Generated by Django 4.2 on 2025-04-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_parametre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id_jury', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MembreJury',
            fields=[
                ('id_membre', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('jury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MembreJury', to='api.jury')),
            ],
        ),
    ]
