# Generated by Django 4.2 on 2025-04-23 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_jury_membrejury'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientMatierePhase',
            fields=[
                ('id_coeffmp', models.AutoField(primary_key=True, serialize=False)),
                ('estPreselection', models.BooleanField()),
                ('coefficient', models.IntegerField()),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CoeffMP', to='api.matiere')),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CoeffMP', to='api.specialite')),
            ],
        ),
    ]
