# Generated by Django 4.2.20 on 2025-05-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dossier_jury_matiere_parametre_specialite_and_more'),
        ('api', '0018_coefficientmatierephase'),
    ]

    operations = [
    ]
