# Generated by Django 4.2.20 on 2025-05-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20250508_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='date_inscription',
            field=models.DateField(auto_now_add=True),
        ),
    ]
